services:
  # --- Serviço do Banco de Dados MySQL ---
  db:
    image: mysql:8.0
    container_name: digicoin_mysql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      # Volume para persistir os dados do banco
      - mysql_data:/var/lib/mysql
      # Mapeia seu script SQL para a pasta de inicialização do MySQL
      - ./mysql.txt:/docker-entrypoint-initdb.d/init.sql
    networks:
      - digicoin-net

  # --- Serviço da Aplicação Django ---
  web:
    build: .
    container_name: digicoin_web
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/midia
    ports:
      # A porta 8000 só é acessível pelo localhost, para o Nginx se conectar
      - "127.0.0.1:8000:8000"
    env_file: .env
    depends_on:
      - db
    networks:
      - digicoin-net

# --- Definições de Volumes e Redes ---
volumes:
  mysql_data:
  static_volume:
  media_volume:

networks:
  digicoin-net: