# Generated by Django 4.2.19 on 2025-05-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_compra_datacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(blank=True, default=False),
        ),
    ]
