# Generated by Django 4.2.19 on 2025-05-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_campanha_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(default=False),
        ),
    ]
