# Generated by Django 4.2.19 on 2025-05-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_campanha_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='predefinida',
        ),
        migrations.AlterField(
            model_name='campanha',
            name='dataFim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='dataInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
