# Generated by Django 4.2.19 on 2025-07-24 23:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_campanha_predefinida_alter_campanha_datafim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='complemento',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
    ]
