# Generated by Django 4.2.19 on 2025-07-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_compra_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='obsEntrega',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
    ]
