# Generated by Django 4.2.19 on 2025-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_compra_obsentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
            preserve_default=False,
        ),
    ]
