# Generated by Django 4.2.19 on 2025-10-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
