# Generated by Django 4.2.19 on 2025-10-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_compra_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pontuacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saldo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
