name: Deploy Aplicativo Django (Digicoin)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DJANGO_PROJECT_REPO_NAME }}:latest 

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        # ### REMOVIDO: Bloco 'env:' inteiro foi removido ###
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Acessa o diretório do projeto
            cd ${{ secrets.DJANGO_PROJECT_DIR }} 

            # --- Cria o docker-compose.yml (com Adminer) ---
            cat << EOF > docker-compose.yml
            version: '3.8' 
            services:
              mysql: 
                image: mysql:8.0
                container_name: digicoin_mysql 
                restart: unless-stopped
                # O env_file lerá as variáveis (incluindo a root pass) do .env
                env_file: .env 
                volumes:
                  - mysql_data:/var/lib/mysql 
                networks:
                  - django-net 

              web: 
                image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DJANGO_PROJECT_REPO_NAME }}:latest 
                container_name: digicoin_web 
                restart: unless-stopped
                command: gunicorn --bind 0.0.0.0:8000 setup.wsgi:application 
                ports:
                  - "127.0.0.1:8000:8000" 
                env_file: .env 
                volumes:
                  - staticfiles:/app/data/staticfiles 
                  - mediafiles:/app/data/mediafiles   
                depends_on:
                  - mysql 
                networks:
                  - django-net 

              adminer:
                image: adminer
                container_name: digicoin_adminer 
                restart: unless-stopped
                ports:
                  - "127.0.0.1:8083:8080" 
                networks:
                  - django-net 

            volumes: 
              mysql_data:
              staticfiles: 
              mediafiles:

            networks: 
              django-net:
            EOF

            # --- Cria o arquivo .env (Usando secrets diretamente) ---
            echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
            echo "DEBUG=False" >> .env
            echo "ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> .env 
            # Usa secrets DB_* diretamente
            echo "DATABASE_URL=mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@mysql:3306/${{ secrets.DB_NAME }}" >> .env 
            
            # Escreve todas as variáveis DB_* e a root pass no .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env # Usa o nome MYSQL_ROOT_PASSWORD para o secret
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env 
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env 
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env 

            echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
            echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
            echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env

            # --- Cria o arquivo mysql.txt (Usando secrets diretamente) ---
            cat << EOF > mysql.txt
            CREATE DATABASE IF NOT EXISTS \`${{ secrets.DB_NAME }}\`;
            CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';
            GRANT ALL PRIVILEGES ON \`${{ secrets.DB_NAME }}\`.* TO '${{ secrets.DB_USER }}'@'%';
            FLUSH PRIVILEGES;
            USE \`${{ secrets.DB_NAME }}\`; 
            SET GLOBAL event_scheduler = ON;
            DELIMITER $$
            CREATE PROCEDURE IF NOT EXISTS desativar_itens_expirados()
            BEGIN
              UPDATE api_desafio SET is_active = FALSE WHERE dataFim < CURDATE() AND is_active = TRUE;
              UPDATE api_produto SET is_active = FALSE WHERE idCampanha_id IN (SELECT id FROM api_campanha WHERE dataFim < CURDATE() AND is_active = TRUE);
              UPDATE api_desafio SET is_active = FALSE WHERE idCampanha_id IN (SELECT id FROM api_campanha WHERE dataFim < CURDATE() AND is_active = TRUE);
              UPDATE api_campanha SET is_active = FALSE WHERE dataFim < CURDATE() AND is_active = TRUE;
            END$$
            DELIMITER ;
            DROP EVENT IF EXISTS desativar_campanhas_event; 
            CREATE EVENT desativar_campanhas_event ON SCHEDULE EVERY 1 DAY STARTS NOW() DO CALL desativar_itens_expirados();
            SELECT 'Script mysql.txt completo executado!' AS status;
            EOF

            # --- Cria a configuração do Nginx ---
            # (Nenhuma mudança aqui, já estava correto)
            cat << EOF > nginx.conf
            server { listen 80; server_name promptweb.com.br www.promptweb.com.br digicoin.promptweb.com.br; return 301 https://\$host\$request_uri; }
            server {
                listen 443 ssl http2; server_name promptweb.com.br www.promptweb.com.br digicoin.promptweb.com.br; 
                ssl_certificate /etc/letsencrypt/live/promptweb.com.br/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/promptweb.com.br/privkey.pem; 
                include /etc/letsencrypt/options-ssl-nginx.conf; ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
                location /static/ { alias ${{ secrets.DJANGO_STATIC_PATH }}; } location /media/ { alias ${{ secrets.DJANGO_MEDIA_PATH }}; }
                location / { proxy_pass http://127.0.0.1:8000; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; }
                location /adminer-mysql/ { proxy_pass http://127.0.0.1:8083/; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; }
            }
            EOF

            # --- Bloco de Administração do Servidor ---
            # (Nenhuma mudança aqui)
            NGINX_CONF_FILE="/etc/nginx/sites-available/promptweb"
            NGINX_LINK_FILE="/etc/nginx/sites-enabled/promptweb"
            sudo /usr/bin/mv $PROJECT_DIR/nginx.conf $NGINX_CONF_FILE
            sudo /usr/bin/ln -sf $NGINX_CONF_FILE $NGINX_LINK_FILE
            if ! sudo /usr/sbin/nginx -t; then echo "Erro Nginx!"; exit 1; fi

            # --- Executa o Deploy ---
            echo "Parando contêineres antigos (preservando volumes)..." 
            docker-compose down --remove-orphans 
            # docker-compose down --volumes --remove-orphans # Comentado por padrão

            echo "Removendo contêineres nomeados (se existirem)..."
            docker rm -f digicoin_mysql || true 
            docker rm -f digicoin_web || true
            docker rm -f digicoin_adminer || true 

            echo "Baixando nova imagem do App..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DJANGO_PROJECT_REPO_NAME }}:latest 

            echo "Iniciando contêiner MySQL..."
            docker-compose up -d mysql 

            # --- ESPERA INTELIGENTE para o MySQL ---
            echo "Aguardando MySQL ficar pronto..."
            timeout=90
            # Usa o secret MYSQL_ROOT_PASSWORD diretamente no comando
            while ! docker-compose exec mysql mysqladmin ping -h localhost -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} --silent; do 
              sleep 3; timeout=$((timeout - 3));
              if [ $timeout -le 0 ]; then echo "Timeout MySQL!"; docker-compose logs mysql; exit 1; fi
            done
            echo "✅ MySQL pronto!"

            # --- EXECUÇÃO DO mysql.txt ---
            echo "Executando comandos do mysql.txt..."
            # Usa o secret MYSQL_ROOT_PASSWORD diretamente no comando
            docker-compose exec -T mysql mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} < mysql.txt 
            if [ $? -ne 0 ]; then echo "Erro ao executar mysql.txt!"; exit 1; fi
            echo "✅ Script mysql.txt executado."

            # --- Inicia o restante dos serviços ---
            echo "Iniciando Web e Adminer..."
            docker-compose up -d web adminer 

            # --- Comandos Django Finais ---
            echo "Coletando arquivos estáticos..."
            docker-compose exec web python manage.py collectstatic --noinput
            
            echo "Aplicando migrações do Django..."
            docker-compose exec web python manage.py migrate --noinput

            echo "Recarregando Nginx..."
            sudo /usr/bin/systemctl reload nginx

            echo "✅ Deploy Django concluído!"
            echo "   App: https://digicoin.promptweb.com.br ,